# Generated by Django 5.1.4 on 2025-04-15 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0002_auto_20250415_0336"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trip",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="trip",
            name="activities",
            field=models.ManyToManyField(to="trips.activity"),
        ),
        migrations.AlterField(
            model_name="trip",
            name="location",
            field=models.CharField(max_length=255),
        ),
    ]
