# Generated by Django 5.0 on 2025-04-28 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_trip_latitude_trip_longitude_alter_trip_activities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='packing_list',
            field=models.TextField(blank=True, null=True),
        ),
    ]
