# Generated by Django 5.0 on 2025-04-28 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_trip_packing_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='travel_tips',
            field=models.TextField(blank=True, null=True),
        ),
    ]
